[[redirects]]
  from = "/cors-proxy/*"
  to = ":splat"
  status = 200
  force = true
[[redirects]]
  from = "/articles/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/feeds/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/cors-proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"